### ISSUE TITLE
LessError: './antd' wasn't found

### ISSUE THREAD

**Issue by afc163** [chenshuai2144/antd-pro-merge-less#15]
<img width="947" alt="image" src="https://user-images.githubusercontent.com/507615/81172427-cfc53980-8fd0-11ea-9187-5d9df74479db.png">

**Comment by chenshuai2144** [comment]
fiexd

**Comment by whereiscode** [comment]
@chenshuai2144 3.x antd 依然报错

**Comment by whereiscode** [comment]
@chenshuai2144 需要特殊配置什么吗？
